### ISSUE TITLE
How to call it directly from the controller or component

### ISSUE THREAD

**Issue by ghost** [sarsha17/angular-loading-spinner#1]
As I have tested, it can only be called using an `ng-click` event on an HTML element. How can I call it directly from a controller? Like so:

``` JavaScript
app.controller("Ctrl", ["spinnerService", function(spinnerService) {
    spinnerService.show("spinner");
});
```

Please do let me know if I am doing anything wrong.

**Comment by msarsha** [comment]
Try inside $onInit

**Comment by ghost** [comment]
@msarsha Tried that as well. Could you please create a fiddle or plunk with a working example of how it should be done?

**Comment by msarsha** [comment]
Hey @itsag 

Since the controller is initialized before the spinners get registered to the `spinnerService`, you will have to wrap your code with `$timeout` so it get invoked after the registration phase:

```javascript
$timeout(function(){
    spinnerService.show("spinner");
}, 0);
```
